fix compile bug:  no member named 'owner'
In v4.4 kernel, compile error:
```
fs/aufs/i_op.c: In function 'au_pin_hdir_set_owner':
fs/aufs/i_op.c:593:28: error: 'struct mutex' has no member named 'owner'
  p->hdir->hi_inode->i_mutex.owner = task;
```

I found commit 7608a43d8f2e02f8b532f8e11481d7ecf8b5d3f9 in linux git
tree in v3.18 changes, option `CONFIG_SMP` has been replaced by
`CONFIG_MUTEX_SPIN_ON_OWNER`.